services:
  ps-app:
    build: .
    container_name: ps-app
    restart: unless-stopped
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    networks:
      - ps-app-network
      - services-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: ps-elastic
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false # Disable SSL for HTTP
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:


networks:
  ps-app-network:
    name: ps-app-network
    driver: bridge

  services-network:
    external: true
    name: services-network
