# Generated by Django 5.1.1 on 2024-10-05 01:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_images_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="trips",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="trips",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="trips_search__febfb0_gin"
            ),
        ),
    ]
