# Generated by Django 5.1.1 on 2024-10-05 01:23

from django.db import migrations
from django.contrib.postgres.search import SearchVector, SearchQuery


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        # Backfill search_vector data
        Trips = apps.get_model("user", "Trips")
        db_alias = schema_editor.connection.alias
        Trips.objects.using(db_alias).update(
            search_vector=SearchVector("name", "feature_text")
        )

    def reverse_func(apps, schema_editor):
        Trips = apps.get_model("user", "Trips")
        db_alias = schema_editor.connection.alias
        Trips.objects.using(db_alias).update(search_vector=None)

    dependencies = [
        ("user", "0003_add_search_vector_gin_index"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
