# Generated by Django 5.1.1 on 2024-10-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_backfill_search_vector"),
    ]

    operations = [
        migrations.RunSQL(
            # SQL for creating the function
            """
            CREATE OR REPLACE FUNCTION haversine(
                lat1 double precision, lon1 double precision, 
                lat2 double precision, lon2 double precision
            )
            RETURNS double precision AS $$
            DECLARE
                R CONSTANT double precision := 6371;  -- Earth's radius in km
                phi1 double precision;
                phi2 double precision;
                delta_phi double precision;
                delta_lambda double precision;
                a double precision;
                c double precision;
            BEGIN
                phi1 := radians(lat1);
                phi2 := radians(lat2);
                delta_phi := radians(lat2 - lat1);
                delta_lambda := radians(lon2 - lon1);
                
                a := sin(delta_phi / 2) ^ 2 + cos(phi1) * cos(phi2) * sin(delta_lambda / 2) ^ 2;
                c := 2 * atan2(sqrt(a), sqrt(1 - a));
                
                RETURN R * c;  -- Distance in km
            END;
            $$ LANGUAGE plpgsql IMMUTABLE;
            """,
            # SQL for reversing the migration (dropping the function)
            """
            DROP FUNCTION IF EXISTS haversine(
                double precision, double precision, 
                double precision, double precision
            );
            """,
        ),
    ]
